server:
  port: 8080
spring:
    redis:
      database: 0
      host: 192.168.1.229
      port: 6379
      password:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
projectName: webDemo
girl:
      name: haha
      age: 18
